version: '3.5'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports: 
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  # api:
  #   image: contract_api:latest
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     PORT: 3000
  #     ENV: local
  #     POSTGRES_SERVER: db
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB_NAME: contract_local
  #     POSTGRES_USERNAME: postgres
  #     POSTGRES_PASSWORD: postgres
  #     COOP_SERVICE_URL: http://coop:8090
  #     USERMGT_SERVICE_URL: http://user:8091
  #     MASTER_DATA_SERVICE_URL: http://master:8092

  db:
    image: postgres:13.7
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    ports:
      - '5434:5432'
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -d $$POSTGRES_DB -h localhost -p 5432 -U $$POSTGRES_USER',
        ]
      interval: 10s
      timeout: 10s
      retries: 60
